# Generated by Django 6.0.3 on 2026-04-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Detection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="crop_images/")),
                ("crop_type", models.CharField(blank=True, max_length=100)),
                ("disease", models.CharField(blank=True, max_length=100)),
                ("confidence", models.FloatField(default=0.0)),
                ("recommendation", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
