# Generated by Django 6.0.3 on 2026-04-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0002_detection_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="detection",
            name="care_tips",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="detection",
            name="prevention",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="detection",
            name="treatment",
            field=models.TextField(blank=True),
        ),
    ]
